[package]
name = "SymLinker"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
colored = "3.0.0"
chrono = "0.4.40"
sysinfo = "0.34.2"
